### ISSUE TITLE
Exceptions not being thrown

### ISSUE THREAD

**Issue by wittling** [tryfan/pymorpheus#2]
I noticed in using this API Wrapper, that any responses non 200 were not getting Exceptions thrown.
It could be the use of the getattr() function on the call, but I am not sure. As a workaround, I had to specifically check the status code and throw the exception in __init__.py.

            r = getattr(requests, method)(url,
                                          headers=self.headers,
                                          verify=self.sslverify,
                                          json=json_string)

            # had to hack this in to get exceptions to raise properly
            if r.status_code != 200:
               raise requests.HTTPError(r)

**Comment by tryfan** [comment]
Excellent suggestion. I added in the error returned from Morpheus as well. #3
